include_recipe 'cookbook_railsbox'
include_recipe 'phantomjs'
include_recipe 'teamcity_build_agent'
include_recipe 'nodejs'
include_recipe 'teamcity_ruby_build_agent'
include_recipe 'teamcity_ruby_build_agent::python'
include_recipe 'teamcity_ruby_build_agent::dotcloud'